<?php namespace App\Models\Loan;

use Illuminate\Database\Eloquent\Model;

class BusinessOperationalDetail extends Model {
    public $table = "loans_businessoperation_details";

    protected $fillable = [
        'loan_id',
        'officepremise_type',
        'approx_value',
        'monthly_rentpaid',
        'mfgpremise_type',
        'approx_land_value',
        'top3_custname_1',
        'top3_annsales_1',
        'top3_relationsince_1',
        'top3_custname_2',
        'top3_annsales_2',
        'top3_relationsince_2',
        'top3_custname_3',
        'top3_annsales_3',
        'top3_relationsince_3',
        'longterm_contracts_type',
        'longterm_name',
        'longterm_years',
        'longterm_ann_contract_value',
        'longterm_numofyear',
        'ao_name_of_debtor_1',
        'ao_amount_outstanding_1',
        'ao_period_outstanding_1',
        'ao_name_of_debtor_2',
        'ao_amount_outstanding_2',
        'ao_period_outstanding_2',
        'ao_name_of_debtor_3',
        'ao_amount_outstanding_3',
        'ao_period_outstanding_3',
        'aud_name_of_debtor_1',
        'aud_amount_outstanding_1',
        'aud_period_outstanding_1',
        'aud_name_of_debtor_2',
        'aud_amount_outstanding_2',
        'aud_period_outstanding_2',
        'aud_name_of_debtor_3',
        'aud_amount_outstanding_3',
        'aud_period_outstanding_3',
        'supplier_name_1',
        'supplier_amount_1',
        'supplier_relation_1',
        'supplier_ref_name_1',
        'supplier_ref_contact_1',
        'supplier_name_2',
        'supplier_amount_2',
        'supplier_relation_2',
        'supplier_ref_name_2',
        'supplier_ref_contact_2',
        'supplier_name_3',
        'supplier_amount_3',
        'supplier_relation_3',
        'supplier_ref_name_3',
        'supplier_ref_contact_3',
        'competitor_name_1',
        'competitor_type_1',
        'competitor_name_2',
        'competitor_type_2',
        'competitor_name_3',
        'competitor_type_3',
        'competitor_name_4',
        'competitor_type_4',
        'fin_positions_1',
        'fin_positions_2',
        'fin_positions_3',
        'fin_positions_4',
        'fin_positions_5',
        'fin_profession_1',
        'fin_profession_2',
        'fin_profession_3',
        'fin_profession_4',
        'fin_profession_5',
        'relationship_type',
        'vendor_service_name',
        'vendor_relation_since',
        'vendor_period_1',
        'vendor_saleamount_1',
        'vendor_products_sold_1',
        'vendor_period_2',
        'vendor_saleamount_2',
        'vendor_products_sold_2',
        'vendor_period_3',
        'vendor_saleamount_3',
        'vendor_products_sold_3',
        'vendor_period_4',
        'vendor_saleamount_4',
        'vendor_products_sold_4',
        'vendor_period_5',
        'vendor_saleamount_5',
        'vendor_products_sold_5',
        'vendor_period_6',
        'vendor_saleamount_6',
        'vendor_products_sold_6'
    ];

    public function getLoan(){
        return $this->belongsTo('App\Models\Loan\Loan','loan_id','id');
    }

    public function getCompetitorDetails(){
        return $this->belongsTo('App\Models\Loan\Loan','loan_id','id');
    }
}